export default [{
    "menuitemndesc": "[Menu1598861013028605]核心参数",
    "__istramenudesc": "文件夹",
    "menuitemlevnbr": 1,
    "menuitemdesc": "核心参数",
    "children": [{
        "menuitemdesc": "公共",
        "menuitemlevnbr": 2,
        "__istramenudesc": "文件夹",
        "menuitemndesc": "[Menu1598941534990403]公共",
        "children": [{
            "menuitemdesc": "费用管理",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1598941572948938]费用管理",
            "children": [{
                "menuitemdesc": "收费公式查询",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1598942739677460]收费公式查询"
            }, {
                "menuitemdesc": "收费产品维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1598946698480265]收费产品维护"
            }, {
                "menuitemdesc": "收费公式维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu160007109739079]收费公式维护"
            }]
        }, {
            "menuitemdesc": "利率管理",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1598952137769683]利率管理",
            "children": [{
                "menuitemdesc": "利率产品维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1598952165140812]利率产品维护"
            }, {
                "menuitemdesc": "实际利率参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu16218382111920]实际利率参数信息"
            }, {
                "menuitemdesc": "市场利率参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1621842784506915]市场利率参数信息"
            }]
        }, {
            "menuitemdesc": "利率优惠计划",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1598951287724835]利率优惠计划",
            "children": [{
                "menuitemdesc": "利率优惠计划维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu159895131707086]利率优惠计划维护"
            }, {
                "menuitemdesc": "利率优惠计划维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1599010615630317]利率优惠计划维护"
            }, {
                "menuitemdesc": "利率优惠维度查询",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1599035495577615]利率优惠维度查询"
            }, {
                "menuitemdesc": "优惠利率参数查询",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1599035721718877]优惠利率参数查询"
            }]
        }, {
            "menuitemdesc": "客户群",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1598953152820534]客户群",
            "children": [{
                "menuitemdesc": "查询客户群对照信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1598954923168835]查询客户群对照信息"
            }, {
                "menuitemdesc": "查询客户群维度",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1615519670081443]查询客户群维度"
            }, {
                "menuitemdesc": "客户群维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1611309373323520]客户群维护"
            }]
        }, {
            "menuitemdesc": "客户参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600221158462936]客户参数",
            "children": [{
                "menuitemdesc": "行政区划代码参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1621907457437130]行政区划代码参数信息"
            }, {
                "menuitemdesc": "地区代码参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu162191259097146]地区代码参数信息"
            }, {
                "menuitemdesc": "客户证件参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1621923742338157]客户证件参数信息"
            }, {
                "menuitemdesc": "客户关系类型参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1621928790826879]客户关系类型参数信息"
            }]
        }, {
            "menuitemdesc": "维度参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600222787862943]维度参数",
            "children": [{
                "menuitemdesc": "维度参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295313229614]维度参数表"
            }, {
                "menuitemdesc": "维度值明细表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295342821658]维度值明细表"
            }]
        }, {
            "menuitemdesc": "汇率管理",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600222937083602]汇率管理",
            "children": [{
                "menuitemdesc": "系统汇率参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295710743566]系统汇率参数信息"
            }, {
                "menuitemdesc": "汇率浮动范围信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295748754286]汇率浮动范围信息"
            }, {
                "menuitemdesc": "汇率杂项参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295784895881]汇率杂项参数信息"
            }, {
                "menuitemdesc": "汇率定价参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623295829580477]汇率定价参数信息"
            }]
        }, {
            "menuitemdesc": "汇率优惠计划",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu161708567739757]汇率优惠计划",
            "children": [{
                "menuitemdesc": "汇率优惠计划维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1617085703306517]汇率优惠计划维护"
            }]
        }, {
            "menuitemdesc": "机构参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600223797602484]机构参数",
            "children": [{
                "menuitemdesc": "机构信息维护",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1600846462380978]机构信息维护"
            }, {
                "menuitemdesc": "银行代码参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296494491747]银行代码参数信息"
            }, {
                "menuitemdesc": "机构工作日参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296529155315]机构工作日参数信息"
            }, {
                "menuitemdesc": "法人代码参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296565828451]法人代码参数信息"
            }, {
                "menuitemdesc": "关系定义参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296605287688]关系定义参数信息"
            }, {
                "menuitemdesc": "机构凭证限额参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296636481924]机构凭证限额参数信息"
            }]
        }, {
            "menuitemdesc": "现金管理",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600224692254200]现金管理",
            "children": [{
                "menuitemdesc": "券别参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296919023764]券别参数信息"
            }, {
                "menuitemdesc": "现金单位参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296952211631]现金单位参数信息"
            }, {
                "menuitemdesc": "离行配钞参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623296858408234]离行配钞参数信息"
            }]
        }, {
            "menuitemdesc": "凭证管理",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1600227040559208]凭证管理",
            "children": [{
                "menuitemdesc": "存折格式参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306281913888]存折格式参数信息"
            }, {
                "menuitemdesc": "重空挂失参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306320116618]重空挂失参数信息"
            }, {
                "menuitemdesc": "密码种类参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306365963353]密码种类参数信息"
            }, {
                "menuitemdesc": "支付密码凭证使用范围参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306404529140]支付密码凭证使用范围参数信息"
            }, {
                "menuitemdesc": "(重要)凭证种类参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306456965461](重要)凭证种类参数信息"
            }, {
                "menuitemdesc": "凭证提示付款期限信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306499184131]凭证提示付款期限信息"
            }, {
                "menuitemdesc": "重控使用范围参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306543560465]重控使用范围参数信息"
            }, {
                "menuitemdesc": "常用密码参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu162330658637239]常用密码参数信息"
            }, {
                "menuitemdesc": "凭证券别参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306622686789]凭证券别参数信息"
            }, {
                "menuitemdesc": "凭证单位参数信息",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1623306660443739]凭证单位参数信息"
            }]
        }]
    }, {
        "menuitemdesc": "贷款",
        "menuitemlevnbr": 2,
        "__istramenudesc": "文件夹",
        "menuitemndesc": "[Menu1599016737404236]贷款",
        "children": [{
            "menuitemdesc": "贷款扣款顺序表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1599016886701486]贷款扣款顺序表",
            "children": []
        }, {
            "menuitemdesc": "请求系统控制表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1600227389713733]请求系统控制表",
            "children": []
        }, {
            "menuitemdesc": "交易参数表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1600227443899999]交易参数表",
            "children": []
        }, {
            "menuitemdesc": "系统参数表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1604030033776862]系统参数表",
            "children": []
        }, {
            "menuitemdesc": "基础参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1616987980952644]基础参数",
            "children": [{
                "menuitemdesc": "贷款扣款顺序表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988026607624]贷款扣款顺序表"
            }, {
                "menuitemdesc": "批量任务控制表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988553388520]批量任务控制表"
            }]
        }, {
            "menuitemdesc": "业务参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1616988227270286]业务参数",
            "children": [{
                "menuitemdesc": "逾期还款罚金参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988585289207]逾期还款罚金参数表"
            }, {
                "menuitemdesc": "费用参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988615707364]费用参数表"
            }, {
                "menuitemdesc": "贷款拨备计提参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988648582202]贷款拨备计提参数表"
            }, {
                "menuitemdesc": "资产杂类参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988677799766]资产杂类参数表"
            }, {
                "menuitemdesc": "贷款代理信息表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988711060884]贷款代理信息表"
            }, {
                "menuitemdesc": "贷款展期规则表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988740626525]贷款展期规则表"
            }, {
                "menuitemdesc": "贷款余额属性表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988776924368]贷款余额属性表"
            }, {
                "menuitemdesc": "费用分层参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988815658374]费用分层参数表"
            }]
        }, {
            "menuitemdesc": "平台参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "文件夹",
            "menuitemndesc": "[Menu1616988242179350]平台参数",
            "children": [{
                "menuitemdesc": "节假日表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988276687296]节假日表"
            }, {
                "menuitemdesc": "系统请求参数",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988327507708]系统请求参数"
            }, {
                "menuitemdesc": "交易参数表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988364661822]交易参数表"
            }, {
                "menuitemdesc": "请求系统控制表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988416211104]请求系统控制表"
            }, {
                "menuitemdesc": "数据库控制表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988451451194]数据库控制表"
            }, {
                "menuitemdesc": "数据库冲正主控制表",
                "menuitemlevnbr": 4,
                "__istramenudesc": "交易",
                "menuitemndesc": "[Menu1616988494992646]数据库冲正主控制表"
            }]
        }]
    }]
}, {
    "menuitemdesc": "系统管理",
    "menuitemlevnbr": 1,
    "__istramenudesc": "文件夹",
    "menuitemndesc": "[Menu1581222896327814]系统管理",
    "children": [{
        "menuitemdesc": "资源管理",
        "menuitemlevnbr": 2,
        "__istramenudesc": "交易",
        "menuitemndesc": "[Menu1591542023530247]资源管理",
        "children": [{
            "menuitemdesc": "交易配置",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591552177182884]交易配置",
            "children": []
        }, {
            "menuitemdesc": "通讯类型",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591552215996104]通讯类型",
            "children": []
        }, {
            "menuitemdesc": "通讯节点",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591552231817765]通讯节点",
            "children": []
        }, {
            "menuitemdesc": "下拉列表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591552326439991]下拉列表",
            "children": []
        }, {
            "menuitemdesc": "数据字典",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu159155236649497]数据字典",
            "children": []
        }, {
            "menuitemdesc": "系统参数",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591552388409751]系统参数",
            "children": []
        }, {
            "menuitemdesc": "交易模板",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1591553693206764]交易模板",
            "children": []
        }, {
            "menuitemdesc": "交易授权条件表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1608278810814662]交易授权条件表",
            "children": []
        }, {
            "menuitemdesc": "交易授权配置表",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1608278856665132]交易授权配置表",
            "children": []
        }, {
            "menuitemdesc": "6673",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1620266666916476]6673",
            "children": []
        }, {
            "menuitemdesc": "40102",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1620272482614214]40102",
            "children": []
        }]
    }, {
        "menuitemdesc": "菜单管理",
        "menuitemlevnbr": 2,
        "__istramenudesc": "文件夹",
        "menuitemndesc": "[Menu1581223207158679]菜单管理",
        "children": [{
            "menuitemdesc": "菜单维护",
            "menuitemlevnbr": 3,
            "__istramenudesc": "交易",
            "menuitemndesc": "[Menu1581223207158680]菜单维护",
            "children": []
        }]
    }]
}]