name: IWORK VUE and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        npm config set registry https://registry.npm.taobao.org 
        npm i
        npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: product
        BUILD_SCRIPT: npm install && npm run build && npm run build:umd
# https://github.com/marketplace/actions/deploy-to-github-pages
