name: IWORK VUE and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    
   - name: Install and Build 🔧
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build
    - run: npm run build:umd

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: product
        BUILD_SCRIPT: npm install && npm run build && npm run build:umd
# https://github.com/marketplace/actions/deploy-to-github-pages
